name = "my-static-site"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
account_id = "21783118d91fac275d5bc116c37da809"
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2021-12-22"
